[default]
DATABASE_URL = "postgresql://postgres:Aidenai17405#@localhost:5432/postgres"
API_KEY = "local-api-key-123"
FERNET_KEY = ""

[production]
DATABASE_URL = "postgresql://postgres:Aidenai17405#@localhost:5432/postgres"
API_KEY = "prod-secret-key"
